name: Post Changelog to Discord

on:
  workflow_run:
    workflows: ["Publish"]  # Имя workflow, после которого должен запускаться этот скрипт
    branches: [main]       # Ветка, для которой триггерится workflow
    types:
      - completed

jobs:
  post-changelog:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run Discord Changelog Notifier
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: python Tools/actions_changelogs_since_last_run.py  # Путь к вашему скрипту
